[package]
name = "exe-look"
version = "0.1.0"
authors = ["Lucius-Q-User <12174eb6@opayq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pelite = "0.7.1"

[patch.crates-io.pelite]
git = "https://github.com/CasualX/pelite"
rev = "28441982879279b04afe2cc2a16f692a2642d6d9"
